from blog import db
from app import app

from blog.home.models import Article




articles = [
    {
        "title": "Flask 博客首页的模块化设计",
        "slug": "flask-blog-homepage-modular-design",
        "summary": "从视图、模板与服务层拆分的角度，整理博客首页的模块化实现方式。",
        "content": "这篇文章介绍如何将博客首页拆分为视图层、服务层和模板层，以便后续扩展文章列表、推荐内容和分页能力。通过模块化设计，可以让首页保持清晰结构，同时降低功能增加时的维护成本。",
        "cover_image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        "is_published": True,
        "is_featured": True,
        "view_count": 128,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "使用 SQLAlchemy 设计文章与标签关系",
        "slug": "sqlalchemy-article-tag-relationship",
        "summary": "讲解多对多关系在文章和标签场景中的建模方式，以及常见查询写法。",
        "content": "文章标签通常适合使用多对多关系建模。通过中间表可以灵活管理文章与多个标签之间的对应关系，并支持按标签筛选文章、统计标签热度等扩展能力。",
        "cover_image": "https://images.unsplash.com/photo-1515879218367-8466d910aaa4",
        "is_published": True,
        "is_featured": False,
        "view_count": 96,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "个人博客中的分类体系应该如何规划",
        "slug": "how-to-plan-blog-categories",
        "summary": "从内容组织和用户浏览体验出发，分析分类设计的基本原则。",
        "content": "分类决定了博客内容的组织方式。合理的分类可以帮助用户快速定位文章主题，也方便站长在后续运营中整理内容结构。通常建议先从少量核心分类开始，避免过度细分。",
        "cover_image": "https://images.unsplash.com/photo-1499750310107-5fef28a66643",
        "is_published": True,
        "is_featured": True,
        "view_count": 205,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "为博客文章设计更清晰的摘要字段",
        "slug": "design-better-post-summary-field",
        "summary": "摘要不是正文截断，而是帮助用户快速判断内容价值的独立信息。",
        "content": "摘要字段适合单独维护，而不是简单从正文里截取。好的摘要应该概括文章主题、突出核心收益，并在首页、归档页和搜索结果中承担内容预览的作用。",
        "cover_image": "https://images.unsplash.com/photo-1455390582262-044cdead277a",
        "is_published": False,
        "is_featured": False,
        "view_count": 17,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "Flask 蓝图拆分实践指南",
        "slug": "flask-blueprint-practice-guide",
        "summary": "介绍如何按模块拆分蓝图，让博客项目结构更清晰。",
        "content": "随着页面和功能增加，单文件路由会变得难以维护。使用蓝图按首页、文章、评论、认证等场景拆分，可以让职责更加清晰，也更利于团队协作。",
        "cover_image": "https://images.unsplash.com/photo-1517430816045-df4b7de11d1d",
        "is_published": True,
        "is_featured": True,
        "view_count": 156,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "如何为博客设计清晰的导航结构",
        "slug": "design-clear-blog-navigation",
        "summary": "从首页、分类页到详情页，梳理导航结构的设计思路。",
        "content": "好的导航结构能够帮助用户快速理解站点内容。博客常见导航包括首页、分类、标签、归档和关于页面，每个入口都应该反映明确的用户需求。",
        "cover_image": "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8",
        "is_published": True,
        "is_featured": False,
        "view_count": 88,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "博客首页卡片布局的设计原则",
        "slug": "blog-card-layout-principles",
        "summary": "围绕封面、标题、摘要和元信息设计更易读的卡片布局。",
        "content": "文章卡片是博客首页最常见的内容呈现形式。合理安排封面图、标题、摘要和作者分类信息，有助于提升扫描效率和点击率。",
        "cover_image": "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
        "is_published": True,
        "is_featured": True,
        "view_count": 132,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "用服务层组织首页文章查询逻辑",
        "slug": "use-service-layer-for-home-queries",
        "summary": "将查询逻辑从视图函数剥离到服务层，提升可维护性。",
        "content": "如果视图函数中同时处理路由、查询、排序和格式化，代码会迅速膨胀。服务层能把首页文章查询逻辑集中管理，便于后续增加筛选和缓存。",
        "cover_image": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97",
        "is_published": True,
        "is_featured": False,
        "view_count": 74,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "为什么博客需要独立的 about 模块",
        "slug": "why-blog-needs-about-module",
        "summary": "about 区域不仅是自我介绍，还承担站点定位说明。",
        "content": "在个人博客中，about 模块可以向读者解释作者身份、内容方向与站点目标。一个清晰的 about 区域能够增强网站的个性表达和信任感。",
        "cover_image": "https://images.unsplash.com/photo-1519389950473-47ba0277781c",
        "is_published": True,
        "is_featured": False,
        "view_count": 61,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "用 slug 提升文章链接可读性",
        "slug": "improve-links-with-slug",
        "summary": "解释为什么文章 URL 不应只使用数字 ID。",
        "content": "slug 能够让链接更具语义，也更方便用户识别文章主题。相比单纯的数字 ID，带有关键词的 URL 在分享、收藏和搜索场景中都更友好。",
        "cover_image": "https://images.unsplash.com/photo-1461749280684-dccba630e2f6",
        "is_published": True,
        "is_featured": False,
        "view_count": 110,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "博客详情页的信息层级应该如何安排",
        "slug": "post-detail-information-hierarchy",
        "summary": "分析标题、元信息、正文与侧边栏在详情页中的视觉顺序。",
        "content": "详情页的核心是阅读体验。通常应优先呈现标题和元信息，再进入正文内容，辅助信息如标签、相关文章和目录则应服务于阅读，而非干扰主体。",
        "cover_image": "https://images.unsplash.com/photo-1522542550221-31fd19575a2d",
        "is_published": True,
        "is_featured": True,
        "view_count": 149,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "如何为博客文章添加推荐标记",
        "slug": "how-to-add-featured-post-flag",
        "summary": "推荐文章机制能帮助首页突出重点内容。",
        "content": "通过设置推荐标记，可以让优质文章在首页、专题页或轮播区域优先展示。推荐机制适合用于展示高质量内容、系列文章或站长重点输出。",
        "cover_image": "https://images.unsplash.com/photo-1516321497487-e288fb19713f",
        "is_published": True,
        "is_featured": True,
        "view_count": 171,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "文章浏览量字段的业务价值",
        "slug": "business-value-of-view-count",
        "summary": "浏览量不仅是展示数字，还能支持热门排序和运营分析。",
        "content": "view_count 看似只是一个简单的整数，但它可以支撑热门文章榜单、趋势观察和用户偏好分析。在博客系统中，这类统计字段非常适合做轻量运营功能。",
        "cover_image": "https://images.unsplash.com/photo-1518186233392-c232efbf2373",
        "is_published": True,
        "is_featured": False,
        "view_count": 223,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "给技术博客添加封面图时要注意什么",
        "slug": "blog-cover-image-considerations",
        "summary": "封面图应服务内容识别，而不是单纯装饰。",
        "content": "封面图可以提升页面视觉吸引力，但不应喧宾夺主。对技术博客而言，统一的视觉风格、合适的尺寸与稳定的资源地址比炫目的效果更重要。",
        "cover_image": "https://images.unsplash.com/photo-1484417894907-623942c8ee29",
        "is_published": True,
        "is_featured": False,
        "view_count": 57,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "Flask 模板继承在博客中的实际用法",
        "slug": "flask-template-inheritance-for-blog",
        "summary": "通过 base 模板复用头部、底部和主题结构。",
        "content": "模板继承可以让博客页面共享统一的布局结构。首页、详情页和表单页都能在基础模板之上扩展各自内容，从而减少重复代码并保持风格统一。",
        "cover_image": "https://images.unsplash.com/photo-1505685296765-3a2736de412f",
        "is_published": True,
        "is_featured": True,
        "view_count": 143,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "文章分类页的筛选体验优化",
        "slug": "category-filter-experience-optimization",
        "summary": "探讨分类页在分页、排序和空状态上的体验细节。",
        "content": "分类页不仅要能展示指定类别的文章，还应兼顾筛选效率和浏览节奏。排序方式、分页位置、空状态提示和面包屑路径都会影响最终体验。",
        "cover_image": "https://images.unsplash.com/photo-1496171367470-9ed9a91ea931",
        "is_published": True,
        "is_featured": False,
        "view_count": 69,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "从零设计博客文章表单",
        "slug": "design-blog-post-form-from-scratch",
        "summary": "文章创建表单应兼顾输入效率、校验与内容完整性。",
        "content": "文章表单通常包含标题、摘要、正文、分类、标签、封面图和发布状态。良好的表单设计不仅提高编辑效率，也能减少数据不完整或格式错误的问题。",
        "cover_image": "https://images.unsplash.com/photo-1451187580459-43490279c0fa",
        "is_published": True,
        "is_featured": False,
        "view_count": 81,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "为什么文章摘要不应自动截取正文",
        "slug": "why-summary-should-not-be-auto-truncated",
        "summary": "自动截断虽然方便，但往往无法传达文章重点。",
        "content": "正文前几句不一定适合作为摘要。一个有意识撰写的摘要可以突出文章价值，帮助用户判断是否值得阅读，也更适合首页和搜索场景。",
        "cover_image": "https://images.unsplash.com/photo-1455390582262-044cdead277a",
        "is_published": True,
        "is_featured": False,
        "view_count": 64,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "博客主题切换的样式组织方式",
        "slug": "theme-switch-style-organization",
        "summary": "浅色与深色主题应通过结构化样式表实现复用。",
        "content": "主题切换通常不是简单替换颜色，而是通过变量、基础样式和主题覆盖来实现。合理的样式组织方式能让后续维护和新增主题更加高效。",
        "cover_image": "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
        "is_published": True,
        "is_featured": True,
        "view_count": 194,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "如何组织博客中的静态资源目录",
        "slug": "organize-blog-static-assets",
        "summary": "从 CSS、图片到脚本，统一静态资源目录结构。",
        "content": "静态资源目录如果缺少规划，项目会随着页面增多而变得混乱。建议按类型和页面场景拆分目录，例如基础样式、主题样式、首页样式和公共图片资源。",
        "cover_image": "https://images.unsplash.com/photo-1517142089942-ba376ce32a2e",
        "is_published": True,
        "is_featured": False,
        "view_count": 52,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "文章列表页的分页设计要点",
        "slug": "pagination-design-for-post-list",
        "summary": "分页不仅影响性能，也直接影响内容浏览节奏。",
        "content": "分页设计要在性能与体验之间做平衡。每页数量、分页控件位置、上一页下一页逻辑以及当前页高亮，都会影响用户的浏览效率。",
        "cover_image": "https://images.unsplash.com/photo-1473091534298-04dcbce3278c",
        "is_published": True,
        "is_featured": False,
        "view_count": 101,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "为博客文章建立统一的命名规范",
        "slug": "blog-post-naming-conventions",
        "summary": "标题、slug 和模板命名统一后，维护成本会明显下降。",
        "content": "统一命名规范能够减少沟通成本，也更利于后期重构。对博客来说，文章 slug、分类名、模板文件名和静态资源名都适合采用可读且一致的规则。",
        "cover_image": "https://images.unsplash.com/photo-1499750310107-5fef28a66643",
        "is_published": True,
        "is_featured": False,
        "view_count": 73,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "博客项目中的数据库初始化流程",
        "slug": "database-init-flow-for-blog",
        "summary": "梳理建表、种子数据和幂等初始化的基本流程。",
        "content": "数据库初始化通常包括创建表结构、插入默认配置、准备作者分类标签以及导入演示文章。幂等设计能够让脚本多次执行而不产生重复数据。",
        "cover_image": "https://images.unsplash.com/photo-1544383835-bda2bc66a55d",
        "is_published": True,
        "is_featured": True,
        "view_count": 211,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "文章详情页中的相关文章推荐策略",
        "slug": "related-posts-strategy",
        "summary": "从分类、标签和热门度三个角度推荐相关文章。",
        "content": "相关文章能提升用户停留时间，也帮助内容形成网络。常见策略包括同分类推荐、同标签推荐以及结合发布时间和浏览量做轻量排序。",
        "cover_image": "https://images.unsplash.com/photo-1516321310764-8d2aa3c2f1c7",
        "is_published": True,
        "is_featured": False,
        "view_count": 124,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "如何在博客中展示站点级配置",
        "slug": "display-site-config-in-blog",
        "summary": "站点名称、副标题和页脚文案适合通过配置表集中管理。",
        "content": "博客中很多文本并不属于单篇文章，而是属于站点级配置，例如 hero 标题、站点描述和页脚内容。集中管理这些字段有助于统一修改和后期扩展。",
        "cover_image": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
        "is_published": True,
        "is_featured": False,
        "view_count": 66,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "博客系统中常见的文章状态设计",
        "slug": "common-post-status-design",
        "summary": "发布、草稿、推荐等状态字段如何协同工作。",
        "content": "文章状态并不只有是否发布一种。随着功能扩展，通常还会涉及推荐、置顶、归档甚至定时发布等语义，因此状态字段的命名与职责划分很关键。",
        "cover_image": "https://images.unsplash.com/photo-1516321497487-e288fb19713f",
        "is_published": True,
        "is_featured": True,
        "view_count": 159,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "如何用 Flask 实现文章详情路由",
        "slug": "implement-post-detail-route-with-flask",
        "summary": "通过 slug 查询文章并渲染详情模板的基础流程。",
        "content": "文章详情页通常通过 slug 定位具体内容。视图函数负责查询文章、处理不存在情况，并将对象传递给模板进行渲染。这个过程是博客 MVP 的核心路径之一。",
        "cover_image": "https://images.unsplash.com/photo-1518770660439-4636190af475",
        "is_published": True,
        "is_featured": False,
        "view_count": 118,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "把文章数据转换为页面展示对象",
        "slug": "convert-article-to-view-model",
        "summary": "解释为什么服务层常常需要返回更适合模板使用的数据结构。",
        "content": "数据库模型往往包含持久化细节，但模板层更关注可直接展示的数据。通过构造视图模型，可以避免模板直接承担太多格式化和关系处理逻辑。",
        "cover_image": "https://images.unsplash.com/photo-1496171367470-9ed9a91ea931",
        "is_published": True,
        "is_featured": False,
        "view_count": 93,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "个人博客为什么适合先做 MVP",
        "slug": "why-build-blog-mvp-first",
        "summary": "先跑通文章展示主链路，再逐步增加评论和后台。",
        "content": "博客功能很容易越做越多，因此优先完成最小可行版本尤为重要。首页、文章详情、基础配置和初始化数据通常就是最合适的第一阶段目标。",
        "cover_image": "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
        "is_published": True,
        "is_featured": True,
        "view_count": 187,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "博客首页推荐区域应该放什么内容",
        "slug": "what-to-show-in-home-featured-section",
        "summary": "推荐区域适合承载精选文章、专题入口和作者表达。",
        "content": "首页推荐区是建立第一印象的关键位置。这里既可以放置精选文章，也可以加入站点简介、专题合集或当前重点输出内容，以强化网站定位。",
        "cover_image": "https://images.unsplash.com/photo-1484417894907-623942c8ee29",
        "is_published": True,
        "is_featured": True,
        "view_count": 146,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "如何让博客首页摘要更统一",
        "slug": "make-home-summaries-consistent",
        "summary": "统一摘要长度与表达风格，可以显著提升首页整洁度。",
        "content": "当首页同时展示多篇文章时，摘要长度不一致会影响整体排版。通过统一摘要规范，可以让卡片高度更稳定，页面视觉也更整洁。",
        "cover_image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        "is_published": True,
        "is_featured": False,
        "view_count": 79,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "为文章系统预留标签扩展能力",
        "slug": "reserve-tag-extensibility-for-posts",
        "summary": "即使暂时不用标签，也建议提前设计好多对多关系。",
        "content": "标签通常会在博客内容积累到一定阶段后发挥价值。提前设计好多对多关系，有助于避免未来迁移成本，并为专题聚合、推荐算法等功能留下空间。",
        "cover_image": "https://images.unsplash.com/photo-1515879218367-8466d910aaa4",
        "is_published": True,
        "is_featured": False,
        "view_count": 84,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "博客页面中的元信息应该展示哪些",
        "slug": "which-post-meta-to-display",
        "summary": "作者、分类、时间与阅读量是最常见的文章元信息。",
        "content": "元信息是帮助读者快速理解内容背景的重要补充。常见字段包括发布时间、分类、作者、标签和阅读量，展示时应注意层级清晰、信息不过载。",
        "cover_image": "https://images.unsplash.com/photo-1451187580459-43490279c0fa",
        "is_published": True,
        "is_featured": False,
        "view_count": 91,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "博客项目中的首页服务函数该怎么命名",
        "slug": "how-to-name-home-service-functions",
        "summary": "函数命名应准确表达查询语义和返回用途。",
        "content": "服务函数名称如果过于笼统，后续维护时会很难判断职责。首页文章查询更适合采用 get_home_articles、get_featured_articles 这类明确表达用途的命名。",
        "cover_image": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
        "is_published": True,
        "is_featured": False,
        "view_count": 58,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "如何为博客增加深色模式",
        "slug": "add-dark-mode-to-blog",
        "summary": "通过独立主题样式和切换状态实现更舒适的阅读体验。",
        "content": "深色模式适合在夜间阅读或低光环境中使用。实现时通常需要拆分颜色变量、主题样式文件和用户偏好保存逻辑，以保持界面一致性。",
        "cover_image": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97",
        "is_published": True,
        "is_featured": True,
        "view_count": 214,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "给博客文章生成测试数据的思路",
        "slug": "generate-blog-seed-data-strategy",
        "summary": "高质量种子数据能让页面联调和样式开发更高效。",
        "content": "测试数据不只是为了填满页面，还应体现真实业务场景。文章长度、摘要风格、浏览量分布和发布状态都可以有意识地做出层次，以便更全面地验证界面表现。",
        "cover_image": "https://images.unsplash.com/photo-1545239351-1141bd82e8a6",
        "is_published": True,
        "is_featured": False,
        "view_count": 137,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "为什么文章详情页要保留分类入口",
        "slug": "why-keep-category-entry-in-post-detail",
        "summary": "分类入口是文章详情页向列表页回流的重要路径。",
        "content": "用户读完一篇文章后，往往希望继续浏览同主题内容。详情页中的分类入口可以帮助用户快速回到同类文章列表，形成连续阅读体验。",
        "cover_image": "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
        "is_published": True,
        "is_featured": False,
        "view_count": 72,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "为博客首页准备多样化的演示文章",
        "slug": "prepare-diverse-demo-posts-for-home",
        "summary": "演示数据越贴近真实场景，越能帮助发现界面问题。",
        "content": "首页联调时，如果所有文章长度和状态都完全一致，很多问题会被掩盖。加入推荐文章、草稿文章、长摘要和高浏览量数据，能更真实地验证页面表现。",
        "cover_image": "https://images.unsplash.com/photo-1516321310764-8d2aa3c2f1c7",
        "is_published": True,
        "is_featured": True,
        "view_count": 165,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "如何控制文章卡片中的文本长度",
        "slug": "control-text-length-in-post-cards",
        "summary": "标题和摘要长度控制能显著提升首页布局稳定性。",
        "content": "文章卡片中的文字如果过长，容易打破栅格布局。通常需要在数据撰写、模板截断和 CSS 行数限制之间共同配合，才能兼顾信息量与整洁度。",
        "cover_image": "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8",
        "is_published": True,
        "is_featured": False,
        "view_count": 95,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "文章发布状态在后台中的交互设计",
        "slug": "publish-status-interaction-design",
        "summary": "草稿与发布切换应简单明确，避免误操作。",
        "content": "在后台编辑文章时，发布状态通常是最常见的控制项之一。清晰的文案、明显的开关状态和保存前提示，能够减少误发布或漏发布问题。",
        "cover_image": "https://images.unsplash.com/photo-1518770660439-4636190af475",
        "is_published": False,
        "is_featured": False,
        "view_count": 24,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "博客文章排序规则的选择建议",
        "slug": "post-sorting-rule-suggestions",
        "summary": "最新优先、热门优先和推荐优先各有适用场景。",
        "content": "文章排序是内容展示策略的一部分。首页通常适合推荐优先加时间倒序，分类页适合时间倒序，专题或榜单则更适合结合浏览量等指标进行排序。",
        "cover_image": "https://images.unsplash.com/photo-1544383835-bda2bc66a55d",
        "is_published": True,
        "is_featured": True,
        "view_count": 182,
        "author_id": 1,
        "category_id": 1,
    },
    {
        "title": "博客内容架构为什么要先定分类再写文章",
        "slug": "define-categories-before-writing-posts",
        "summary": "提前明确分类有助于维持长期内容结构的一致性。",
        "content": "如果分类体系完全随写随定，长期下来容易产生命名混乱和主题重叠。先确定核心分类，再逐步填充文章，有助于博客形成更稳定的内容架构。",
        "cover_image": "https://images.unsplash.com/photo-1499750310107-5fef28a66643",
        "is_published": True,
        "is_featured": False,
        "view_count": 86,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "Flask 博客项目中的模板目录组织",
        "slug": "organize-template-directories-in-flask-blog",
        "summary": "按模块拆分模板目录更适合后续页面扩展。",
        "content": "模板目录通常既可以按页面类型拆，也可以按蓝图模块拆。在博客项目中，首页、详情页和后台表单页往往更适合按照功能模块进行归类。",
        "cover_image": "https://images.unsplash.com/photo-1517142089942-ba376ce32a2e",
        "is_published": True,
        "is_featured": False,
        "view_count": 78,
        "author_id": 1,
        "category_id": 2,
    },
    {
        "title": "如何让博客初始数据更适合前端联调",
        "slug": "make-seed-data-better-for-ui-debugging",
        "summary": "合理分布文章状态和长度，能够更快暴露布局问题。",
        "content": "前端联调阶段最怕只有少量、过于整齐的数据。多样化的初始化文章可以帮助发现溢出、空状态、推荐区排列和分页边界等真实问题。",
        "cover_image": "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
        "is_published": True,
        "is_featured": True,
        "view_count": 153,
        "author_id": 1,
        "category_id": 1,
    },
]


def upsert_articles():
    for article_data in articles:
        exists = Article.query.filter_by(slug=article_data["slug"]).first()
        if exists:
            continue
        db.session.add(Article(**article_data))
    db.session.commit()




if __name__ == '__main__':
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///blog.db"
    with app.app_context():
        upsert_articles()